version: '3'

services:
  app:
    build: ./app
    container_name: app
    expose:
      - "3002: 3002"
  app1:
    build: ./app1
    container_name: app1
    ports:
      - "3000:3000"

  app2:
    build: ./app2
    container_name: app2
    ports:
      - "3001:3001"

  nginx:
    image: openresty/openresty:alpine
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - app1
      - app2